Module3 task1
htmlacademy-react/1136803-guess-melody-5 pull request #4
Opened 2020-10-07 22:50 UTC by ildarjans

2020-10-11 23:28 UTC, sahaviev commented on src/const.js
> +  ERROR_COUNT: 3,
ERROR_COUNT => **MAX_ERROR_COUNT**

2020-10-11 23:29 UTC, sahaviev commented on src/mocks/questions.js
> +export default [
Используй здесь тоже именнованный экспорт

2020-10-11 23:31 UTC, sahaviev commented on src/components/game/game.jsx
> +export class Game extends PureComponent {
PureComponent => **React.PureComponent**

2020-10-11 23:58 UTC, sahaviev commented on src/components/game-genre/game-genre.jsx
> +                      });
Вытащи в отдельную функцию

2020-10-12 09:36 UTC, sahaviev requested changes
Много что на консультации обсуждали и поэтому отправляю на доработку)

2020-10-15 22:08 UTC, sahaviev commented on src/components/artist-input/artist-input.jsx
> +  question: artistQuestionPropTypes,
У тебя **artistQuestionPropTypes** тоже обязательный

2020-10-15 22:08 UTC, sahaviev commented on src/components/artist-prop-types/artist-answers.js
> +export const artistAnswerPropTypes = PropTypes.shape({
Назови с большой буквы проптайпс

2020-10-15 22:09 UTC, sahaviev commented on src/components/artist-prop-types/artist-question.js
> +export const artistQuestionPropTypes = PropTypes.shape({
Назови с большой буквы проптайпс

2020-10-15 22:14 UTC, sahaviev commented on src/components/game-genre/game-genre.jsx
> +    const {genre, answers} = this.props.question;
Я бы вытащил из state **answers** без алиаса и не стал бы деструктурировать **question**.
Просто писал бы question.answer, question.genre

2020-10-15 22:15 UTC, sahaviev commented on src/components/game-artist/game-artist.jsx
> +    const {answers, song} = question;
Избыточная на мой взгляд деструктиризация **question**

2020-10-15 22:15 UTC, sahaviev requested changes
Отписал в комментариях что нужно пофиксить )

2020-10-16 22:56 UTC, ildarjans commented on src/components/artist-prop-types/artist-question.js
> +export const artistQuestionPropTypes = PropTypes.shape({
Это обычный объект. Не по критериям будет.

2020-10-20 23:27 UTC, sahaviev approved these changes
🔥🔥🔥

2020-10-20 23:28 UTC, merged